#!/bin/bash

echo "Hello World!"
echo Bootstrap/START


# sudo apt-get update

# iptables -A INPUT -p tcp --destination-port 3306 -j ACCEPT

# sudo apt-get update --fix-missing



echo Bootstrap/OK
echo "End of Bootstrap Script"