#
# CHENGLONG ZOU
# 2015/16
#
box = 'debian-7.0-amd64.box' # https://www.dropbox.com/s/si19tbftilcuipz/debian-7.0-amd64.box
box_url = box # check if file exists else download from remote path
box_memory = "1024"
box_cpu = "1"
nodes = [
    {:hostname => 'sandBox', :ip => '192.168.56.101', :box => box, :shared_folder=>'../monitor',
     :shared_folder_as=> '/home/vagrant/monitor'}, # :port_fwd=> 5000}, # contains the pc-clients && log monitor
    {:hostname => 'benchBox', :ip => '192.168.56.2', :box => box, :shared_folder=>'../simulator',
     :shared_folder_as=> '/home/vagrant/simulator'} # this contains the pc-benchmarking
]
Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      puts "BOX/LOAD"
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] # capat: hostnamectl
      nodeconfig.vm.box_url = box_url
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.provider :virtualbox do |vm|
        vm.customize [
                         "modifyvm", :id,
                         # "--cpuexecutioncap", "50",
                         "--memory", box_memory.to_s,
                         "--cpus", box_cpu.to_s,
                     ]
      end
      #config.vm.provision :shell, path: "scripts/ugrade-puppet.sh"
      #nodeconfig.vm.provision :shell, path: "scripts/bootstrap"
      if node[:shared_folder]
        puts "sharing a folder"
        nodeconfig.vm.synced_folder node[:shared_folder], node[:shared_folder_as]
      else
        puts "no sharing folder"
      end

      if node[:port_fwd]
        puts "fwd port"
        nodeconfig.vm.network "forwarded_port", guest: node[:port_fwd], host: node[:port_fwd]
        # nodeconfig.vm.network :private_network, ip: "192.168.56.123"
      end

      nodeconfig.vm.provision :shell, inline: "echo 'Sara is my Cat & Tor is my Dog!' > /etc/motd"



    end
  end
  puts "PUPPET/LOAD"
  config.vm.provision :puppet do |puppet|
    # puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.options= ['--verbose', '--debug']
    puppet.facter = {
        "is_vagrant" => true
    }
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file = "default-owncloud.pp"
  end
  puts "VAGRANT/OK"
end
