import psutil
import datetime



class PerformanceCounter:

    Type = None
    # have a live log appended



    def __init__(self, type, spec, bool):
        print '//constructor:PerformanceCounter'
        self.Type = type # memory or processes or disk or network
        self.log_file = self.Type + '_append.log'
        self.logger = open(self.log_file, 'w').close() # clear the file


    def NextValue(self):
        to_execute = getattr(self, 'do'+self.Type)
        value = to_execute()
        print value
        with open(self.log_file, 'a') as file:
            file.write(value) # append text
            file.write('\n') # new line
        return value


    def doNetwork(self): # network traffic , in / out  {unit}
        print 'doNetwork'



    def doProcess(self): # cpu time %
        print 'doProcess'
        # en el de cristian se pilla de todos los cores por separado luego se juntan...
        process = 'TODO'
        tstamp =  datetime.datetime.now().isoformat()
        return '{} {} {}'.format(process, tstamp, psutil.cpu_percent(interval=None, percpu=False))


    def doDisk(self): # input output % time {write/read unit}
        print 'doDisk'
        # how to get the hdd usage??
        process = 'TODO'
        tstamp =  datetime.datetime.now().isoformat()
        return '{} {} {}'.format(process, tstamp, psutil.disk_usage('/').percent)



    def doMemory(self): # % memory usage : {units/%}
        print 'doMemory'
        # how to get the ram usage with psutil???
        #total = psutil.virtual_memory().total
        #active = psutil.virtual_memory().active
        #print active
        #print total
        #percent = (active*100/total)
        # todo check static process id generated by the stacksync or owncloud client and located at path /tmp/s.pid
        # overhead a reading a file... each time, should defined at class atribute level.
        process = 'TODO'
        tstamp =  datetime.datetime.now().isoformat()
        return '{} {} {}'.format(process, tstamp, psutil.virtual_memory().percent)




if __name__ == '__main__':
    print 'Test main program returning values'